; Czech translation of Tauri's NSIS installer strings.
; Tauri does not ship a Czech.nsh, so without this file every Tauri-specific
; text in the Czech installer/uninstaller renders as an empty string.
; Keys mirror crates/tauri-bundler/.../nsis/languages/English.nsh 1:1.
LangString addOrReinstall ${LANG_CZECH} "Přidat / přeinstalovat součásti"
LangString alreadyInstalled ${LANG_CZECH} "Již nainstalováno"
LangString alreadyInstalledLong ${LANG_CZECH} "${PRODUCTNAME} ${VERSION} je již nainstalován. Vyberte požadovanou operaci a pokračujte tlačítkem Další."
LangString appRunning ${LANG_CZECH} "{{product_name}} je spuštěn! Nejprve ho prosím ukončete a zkuste to znovu."
LangString appRunningOkKill ${LANG_CZECH} "{{product_name}} je spuštěn!$\nKlepnutím na OK ho ukončíte"
LangString chooseMaintenanceOption ${LANG_CZECH} "Zvolte operaci údržby, kterou chcete provést."
LangString choowHowToInstall ${LANG_CZECH} "Zvolte, jak chcete ${PRODUCTNAME} nainstalovat."
LangString createDesktop ${LANG_CZECH} "Vytvořit zástupce na ploše"
LangString dontUninstall ${LANG_CZECH} "Neodinstalovávat"
LangString dontUninstallDowngrade ${LANG_CZECH} "Neodinstalovávat (přechod na nižší verzi bez odinstalace je u tohoto instalátoru zakázán)"
LangString failedToKillApp ${LANG_CZECH} "Nepodařilo se ukončit {{product_name}}. Nejprve ho prosím zavřete a zkuste to znovu"
LangString installingWebview2 ${LANG_CZECH} "Instaluje se WebView2…"
LangString newerVersionInstalled ${LANG_CZECH} "Je již nainstalována novější verze ${PRODUCTNAME}! Instalace starší verze se nedoporučuje. Pokud ji opravdu chcete nainstalovat, je lepší nejdříve odinstalovat současnou verzi. Vyberte požadovanou operaci a pokračujte tlačítkem Další."
LangString older ${LANG_CZECH} "starší"
LangString olderOrUnknownVersionInstalled ${LANG_CZECH} "V systému je nainstalována $R4 verze ${PRODUCTNAME}. Před instalací se doporučuje současnou verzi odinstalovat. Vyberte požadovanou operaci a pokračujte tlačítkem Další."
LangString silentDowngrades ${LANG_CZECH} "Přechod na nižší verzi je u tohoto instalátoru zakázán, tichou instalaci nelze provést. Použijte prosím instalátor s grafickým rozhraním.$\n"
LangString unableToUninstall ${LANG_CZECH} "Odinstalace se nezdařila!"
LangString uninstallApp ${LANG_CZECH} "Odinstalovat ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_CZECH} "Před instalací odinstalovat"
LangString unknown ${LANG_CZECH} "neznámá"
LangString webview2AbortError ${LANG_CZECH} "Instalace WebView2 se nezdařila! Aplikace bez něj nemůže běžet. Zkuste instalátor spustit znovu."
LangString webview2DownloadError ${LANG_CZECH} "Chyba: stažení WebView2 se nezdařilo – $0"
LangString webview2DownloadSuccess ${LANG_CZECH} "Zavaděč WebView2 byl úspěšně stažen"
LangString webview2Downloading ${LANG_CZECH} "Stahuje se zavaděč WebView2…"
LangString webview2InstallError ${LANG_CZECH} "Chyba: instalace WebView2 skončila s kódem $1"
LangString webview2InstallSuccess ${LANG_CZECH} "WebView2 byl úspěšně nainstalován"
LangString deleteAppData ${LANG_CZECH} "Smazat data aplikace"
